In [10]:
import pandas as pd

# pull from Kaggle 
aviation_df = pd.read_csv('/Users/danieldaquila/Documents/GradSchool/COMP4447/homeworks/Final_Project/AviationData.csv', encoding="ISO-8859-1")

aviation_df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.Flight,Air.Carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.Phase.of.Flight,Report.Status,Publication.Date
0,20181217X10943,Accident,GAA19CA098,2018-12-16,"Grangville, ID",United States,45.583611,-115.681667,PVT,NaN,...,Positioning,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Preliminary,2018-12-18
1,20181217X25746,Accident,GAA19CA097,2018-12-15,"MORIARTY, NM",United States,34.970000,-106.000000,NaN,MORIARTY MUNI,...,Personal,NaN,NaN,NaN,NaN,1.0,VMC,NaN,Preliminary,2018-12-20
2,20181213X41114,Accident,ERA19LA065,2018-12-13,"Punta Gorda, FL",United States,26.925278,-82.001111,PGD,Punta Gorda,...,Personal,NaN,NaN,NaN,1.0,NaN,VMC,APPROACH,Preliminary,2018-12-21
3,20181213X45528,Accident,CEN19FA044,2018-12-13,"Valparaiso, IN",United States,41.451667,-87.004444,VPZ,Porter County Rgnl,...,Personal,NaN,1.0,NaN,NaN,NaN,VMC,TAKEOFF,Preliminary,2018-12-19
4,20181214X90303,Accident,GAA19CA096,2018-12-11,"Hartford, WI",United States,43.330278,-88.326111,HXF,Hartford Muni,...,Personal,NaN,NaN,NaN,NaN,1.0,VMC,NaN,Preliminary,2018-12-18

In [11]:
aviation_df.drop(['Investigation.Type', 'Airport.Code', 'Airport.Name', 'Engine.Type', 'FAR.Description', 'Schedule', 'Air.Carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Report.Status', 'Publication.Date'], axis=1, inplace=True)
aviation_df

,Event.Id,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Injury.Severity,Aircraft.Damage,Aircraft.Category,Registration.Number,Make,Model,Amateur.Built,Number.of.Engines,Purpose.of.Flight,Weather.Condition,Broad.Phase.of.Flight
0,20181217X10943,GAA19CA098,2018-12-16,"Grangville, ID",United States,45.583611,-115.681667,Non-Fatal,Substantial,Airplane,N4385B,Cessna,170,No,1.0,Positioning,NaN,NaN
1,20181217X25746,GAA19CA097,2018-12-15,"MORIARTY, NM",United States,34.970000,-106.000000,Non-Fatal,Substantial,Airplane,N188H,Cessna,180,No,1.0,Personal,VMC,NaN
2,20181213X41114,ERA19LA065,2018-12-13,"Punta Gorda, FL",United States,26.925278,-82.001111,Non-Fatal,Substantial,Airplane,N145MM,CZECH SPORT AIRCRAFT AS,Piper Sport,No,1.0,Personal,VMC,APPROACH
3,20181213X45528,CEN19FA044,2018-12-13,"Valparaiso, IN",United States,41.451667,-87.004444,Fatal(1),Destroyed,Airplane,N6785P,Piper,PA24,No,1.0,Personal,VMC,TAKEOFF
4,20181214X90303,GAA19CA096,2018-12-11,"Hartford, WI",United States,43.330278,-88.326111,Non-Fatal,Substantial,Airplane,N6650M,Beech,36,No,1.0,Personal,VMC,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82630,20041105X01764,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,Cessna,501,No,NaN,Personal,VMC,APPROACH
82631,20001218X45448,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,Rockwell,112,No,1.0,Personal,IMC,CRUISE
82632,20061025X01555,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,Fatal(3),Destroyed,NaN,N5142R,Cessna,172M,No,1.0,Personal,IMC,CRUISE
82633,20001218X45447,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,PIPER,PA24-180,No,1.0,Personal,UNK,UNKNOWN
82634,20001218X45444,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,STINSON,108-3,No,1.0,Personal,UNK,CRUISE

## List the reason for dropping each column here

In [12]:
aviation_df.isna().sum()

Event.Id                     0
Accident.Number              0
Event.Date                   0
Location                    75
Country                    507
Latitude                 53903
Longitude                53912
Injury.Severity              0
Aircraft.Damage           2592
Aircraft.Category        56735
Registration.Number       3582
Make                        73
Model                      102
Amateur.Built              627
Number.of.Engines         4609
Purpose.of.Flight         4550
Weather.Condition         2708
Broad.Phase.of.Flight     6503
dtype: int64

In [13]:
aviation_df = aviation_df.rename(columns={"Event.Id":"Event_ID", "Accident.Number":"Accident_Number", "Event.Date":"Event_Date", "Injury.Severity":"Injury_Severity", "Aircraft.Damage":"Aircraft_Damage", "Aircaft.Category":"Aircraft_Category", "Registration.Number":"Registration_Number", "Amateur.Built":"Amateur_Built", "Number.of.Engines":"Number_Engines", "Purpose.of.Flight":"Purpose_Flight", "Weather.Condition":"Weather_Condition", "Broad.Phase.of.Flight":"Broad_Phase_Flight"})
aviation_df

,Event_ID,Accident_Number,Event_Date,Location,Country,Latitude,Longitude,Injury_Severity,Aircraft_Damage,Aircraft.Category,Registration_Number,Make,Model,Amateur_Built,Number_Engines,Purpose_Flight,Weather_Condition,Broad_Phase_Flight
0,20181217X10943,GAA19CA098,2018-12-16,"Grangville, ID",United States,45.583611,-115.681667,Non-Fatal,Substantial,Airplane,N4385B,Cessna,170,No,1.0,Positioning,NaN,NaN
1,20181217X25746,GAA19CA097,2018-12-15,"MORIARTY, NM",United States,34.970000,-106.000000,Non-Fatal,Substantial,Airplane,N188H,Cessna,180,No,1.0,Personal,VMC,NaN
2,20181213X41114,ERA19LA065,2018-12-13,"Punta Gorda, FL",United States,26.925278,-82.001111,Non-Fatal,Substantial,Airplane,N145MM,CZECH SPORT AIRCRAFT AS,Piper Sport,No,1.0,Personal,VMC,APPROACH
3,20181213X45528,CEN19FA044,2018-12-13,"Valparaiso, IN",United States,41.451667,-87.004444,Fatal(1),Destroyed,Airplane,N6785P,Piper,PA24,No,1.0,Personal,VMC,TAKEOFF
4,20181214X90303,GAA19CA096,2018-12-11,"Hartford, WI",United States,43.330278,-88.326111,Non-Fatal,Substantial,Airplane,N6650M,Beech,36,No,1.0,Personal,VMC,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82630,20041105X01764,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,Fatal(1),Destroyed,NaN,N15NY,Cessna,501,No,NaN,Personal,VMC,APPROACH
82631,20001218X45448,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,Fatal(2),Destroyed,NaN,N1168J,Rockwell,112,No,1.0,Personal,IMC,CRUISE
82632,20061025X01555,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,Fatal(3),Destroyed,NaN,N5142R,Cessna,172M,No,1.0,Personal,IMC,CRUISE
82633,20001218X45447,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,Fatal(4),Destroyed,NaN,N5069P,PIPER,PA24-180,No,1.0,Personal,UNK,UNKNOWN
82634,20001218X45444,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,Fatal(2),Destroyed,NaN,NC6404,STINSON,108-3,No,1.0,Personal,UNK,CRUISE

In [14]:
aviation_df['Aircraft_Damage'].unique()

array(['Substantial', 'Destroyed', 'Minor', nan], dtype=object)